### ISSUE TITLE
APPSERVICE mode requires a configuration Bean

### ISSUE THREAD

**Issue by enekonieto** [benkuly/matrix-spring-boot-sdk#9]
After migrating my app from client mode to app service (following steps in the README), I get following error while building:
```
Description:

Parameter 1 of method appserviceBotServiceHelper in net.folivo.matrix.bot.config.MatrixAppserviceBotAutoconfiguration required a bean of type 'net.folivo.matrix.appservice.config.AppserviceProperties' that could not be found.


Action:

Consider defining a bean of type 'net.folivo.matrix.appservice.config.AppserviceProperties' in your configuration.
```

I didn't need any Bean for client mode, it was enough with `application.yml`. I have added the `appservice` section in the configuration and I didn't find no more special configuration in samples. Did I miss something?

Full stack (sorry, I got it in one line):
`2021-03-27 12:44:46.233  WARN 18225 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'privateTravelRestController' defined in file [/home/eneko/dev/okupamicoche/okupamicoche/build/classes/kotlin/main/eu/fosil/okupamicoche/spring/controller/PrivateTravelRestController.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'useCaseService' defined in file [/home/eneko/dev/okupamicoche/okupamicoche/build/classes/kotlin/main/eu/fosil/okupamicoche/spring/services/UseCaseService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'matrixService' defined in file [/home/eneko/dev/okupamicoche/okupamicoche/build/classes/kotlin/main/eu/fosil/okupamicoche/spring/services/MatrixService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'matrixClient' defined in class path resource [net/folivo/matrix/restclient/config/MatrixClientAutoconfiguration.class]: Unsatisfied dependency expressed through method 'matrixClient' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'persistentSyncBatchTokenService' defined in class path resource [net/folivo/matrix/bot/config/MatrixBotAutoconfiguration.class]: Unsatisfied dependency expressed through method 'persistentSyncBatchTokenService' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'matrixUserService' defined in class path resource [net/folivo/matrix/bot/config/MatrixBotAutoconfiguration.class]: Unsatisfied dependency expressed through method 'matrixUserService' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appserviceBotServiceHelper' defined in class path resource [net/folivo/matrix/bot/config/MatrixAppserviceBotAutoconfiguration.class]: Unsatisfied dependency expressed through method 'appserviceBotServiceHelper' parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'net.folivo.matrix.appservice.config.AppserviceProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

Thanks!

**Comment by benkuly** [comment]
Are you sure, you added `matrix.appservice` properties?

**Comment by enekonieto** [comment]
Wow, so quick...

This is the matrix part of my application.yml (tokens edited):
```
matrix:
  bot:
    # The domain-part of matrix-ids. E. g. example.org when your userIds look like @unicorn:example.org
    serverName: synapse
    # The localpart (username) of the user associated with the application service
    # or just the username of your bot.
    username: test
    # (optional) Display name for the bot user.
    displayname: Okupa mi coche
    # (optional) The mode you want to use to create a bot. Default is CLIENT. The other is APPSERVICE.
    mode: APPSERVICE
    # (optional) Configure how users managed by your bot do automatically join rooms.
    # ENABLED allows automatic joins to every invited room.
    # DISABLED disables this feature.
    # Default is RESTRICTED, which means, that only automatic joins to serverName are allowed.
    autoJoin: DISABLED
    # (optional) Configure if ALL membership changes should be tracked/saved with help of MatrixAppserviceRoomService
    # or only membership changes of users, which are MANAGED by the bridge. Default is ALL (no tracking/saving).
    trackMembership: ALL
    # Connection settings to the database (only r2dbc drivers are supported)
    migration:
      url: jdbc:h2:file:./matrix
      username: sa
      password:
    # Connection setting to the database for migration purpose only (only jdbc drivers ar supported)
    database:
      url: r2dbc:h2:file:///./matrix
      username: sa
      password:
  client:
    homeServer:
      # The hostname of your Homeserver.
      hostname: synapse
      # (optional) The port of your Homeserver. Default is 443.
      port: 8008
      # (optional) Use http or https. Default is true (so uses https).
      secure: false
    # The token to authenticate against the Homeserver.
    token: SECRET
  appservice:
    # A unique token for Homeservers to use to authenticate requests to application services.
    hsToken: SECRET
    # A list of users, aliases and rooms namespaces that the application service controls.
    namespaces:
      users: [ ]
      aliases:
        - localpartRegex: "#viaje_.*"
      rooms: [ ]
```
